is_debug: true
jwt:
  secret: q1w2e3r4t5y6
listen:
  type: port
  bind_id: 0.0.0.0
  port: 10001
mongodb:
  host: localhost
  port: 27017
  username: senizdegen
  auth_db: sdu-housing
  database: sdu-housing
  collection: users